version: "3"
services:
  wordpress:
    container_name: wordpress
    build: requierement/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
  # depends_on:
  #   - mariadb
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    #restart: unless-stopped

  nginx:
    build: requierement/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    env_file:
      .env
    volumes:
      - wp_files:/var/www/html
    # depends_on:
    #   - wordpress
    networks:
      - inception
    restart: unless-stopped


volumes:
     wp_database: 
       driver: local
       driver_opts:
         type: none
         device: /Users/${USER}/data/wp_database
         o: bind
     wp_files:
       driver: local
       driver_opts:
         type: none
         device: /Users/${USER}/data/wp_files
         o: bind


networks:
  inception: {}