version: "3"

services:

  nginx:
    build: requierement/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    env_file:
      .env
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    restart: unless-stopped


volumes:
     wp_database: 
       driver: local
       driver_opts:
         type: none
         device: /Users/${USER}/data/wp_database
         o: bind
     wp_files:
       driver: local
       driver_opts:
         type: none
         device: /Users/${USER}/data/wp_files
         o: bind


networks:
  inception: {}