FROM debian:buster

RUN			apt-get update 
RUN			apt-get install wget -y
RUN			apt-get install php7.3 -y
RUN			apt-get install php7.3-fpm -y 
RUN			apt-get install php7.3-mysql -y

COPY		./conf/www.conf /etc/php/7.3/fpm/pool.d/

RUN			mkdir /usr/share/wordpress
WORKDIR		/usr/share/wordpress

COPY		tools/configure.sh ./
RUN			chmod +x ./configure.sh

EXPOSE		9000

ENTRYPOINT	./configure.sh
